// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "68afd514d52e42001e56addc407069a9"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"baddb71fc4e0987fbfbdbc8cb0523996": "1f8b08000000000000ffdc56b16edc300cddfd158292a948e2762a7073c70e013a0637a816ad536a4baa4415080aff7b21c7f6e96cea1aa4d7e5568a7c7c249f28fdae18e3b7a139402ff88ef103a2dbd5f573b0e6fed5fa60bdaaa5172dde7ffc5cbfda6ef85d8a93d06aa3515b13f88e2528c6b8360145d77d43708b91318e2f0e5202fbfd191a1ce347bbf3d681470d21f3668caba6b351261bbff5d0a6d09b3a4b584f0ec314322c881e7e46ed21c53e6df026c37ef116528e80a27bcc99b4a20b5065c03c3ae58584abab4b9b5ff6c7f59515cdb50a3120b82f101aaf5df2a76a0be8b551c7da7a6dbe825178e03bf6e904cc467411030522bc172f470c8dd0af5a536865b9998c71237a58d9b6c4b3c3e12e8f4e7be9518c75bc1da122b0ceb63b732367389741535b8cfb2a273077fca8a7f72a5292c31f8f6885ae15433644791bdd665c13b7a74552b32ef6244863fb5e185940d90ce764205ec51e0c9628acf4c8684d9e4d57d242db09554cbb1177593cff48637b175979a6b373b5c61cdeb451feb2a472896d35420c7c5e67d54c65a441359192f5fc6978df1aa21b94af7ff2224e0ffa2573e67f043aa7f90f959e3e75a7799749388108de107ae50f1f2edbf7e53f51a072f6a51baa3f010000ffff303cdbe1930a0000",
		"c8ca07d10aeea8e65542ca8e7e1047bd": "1f8b08000000000000ff8c923f4fc3400cc5773e8575dde30ac452a5110c6563843deab9ed89fb535d8c92cabaef8ec22569822ad12db27f7e2f7ebef240a4a173d6375b75623e6f10dbb62ddaa722c4233eaed7cff8cac1a9ea0100a034baeaa96683485dedce968a7d70e84c677c53a2d103c7862d55bb8cc0fbd0ced54c7c9f75cda42b918ffc955289633123d6f82f8864b7aa217b50708a74c87f79db1f6b0eaee89c5598154456d93aa5acb8af998e215e8029baad122952bac2b88045563bcfd1d0344d9ee325c3ff8781229f141b137c4a28f22bddaf3846348b69eac20bcca61679dd99d9ed2d07f971d30c05cfe4b95a188ec5091359bd193b45f0e72c3ab4de865adf719a651abd664a0a70ee8473a71267698be0f51425f66fb6fa090000ffff38ab3d24ba020000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("github.com/deislabs/porter/pkg/mixin/feed/templates", "./templates")
		b.SetResolver("atom-template.xml", packr.Pointer{ForwardBox: gk, ForwardPath: "c8ca07d10aeea8e65542ca8e7e1047bd"})
		}()


	func() {
		b := packr.New("schema", "./schema")
		b.SetResolver("gcloud.json", packr.Pointer{ForwardBox: gk, ForwardPath: "baddb71fc4e0987fbfbdbc8cb0523996"})
		}()

	return nil
}()
